apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentgateway.fullname" . }}-config
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    # yaml-language-server: $schema=https://agentgateway.dev/schema/config
    binds:
    - port: 3000
      listeners:
      - routes:
        - name: anthropic
          matches:
          - path:
              pathPrefix: /
            headers:
            - name: x-provider
              value:
                exact: anthropic
          backends:
          - ai:
              name: anthropic
              provider:
                anthropic:
                  model: claude-sonnet-4-20250514
          policies:
            cors:
              allowOrigins: ["*"]
              allowHeaders: ["*"]
            backendAuth:
              key: "$ANTHROPIC_API_KEY"
        - name: gemini
          matches:
          - path:
              pathPrefix: /
            headers:
            - name: x-provider
              value:
                exact: gemini
          backends:
          - ai:
              name: gemini
              provider:
                gemini:
                  model: gemini-2.5-flash
          policies:
            cors:
              allowOrigins: ["*"]
              allowHeaders: ["*"]
            backendAuth:
              key: "$GEMINI_API_KEY"

